name = "educonnect-v2-staging"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "educonnect-staging"
database_id = "6fd55c8b-e491-416d-ba46-cd4ff1a99df8"
